# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ecac0d69a49cd23fb1820efae19b529161b85218c017f68c8fbe2d8defb34d00886fde771e1e444d9e99513a802eac933e06d1fa1f8e3566a291a59abb9c70a

test:
  secret_key_base: e8211f24f0b952a32120ff5025ff7bdb00f00e331a97d4c6cbc36ace98c5e7d96e52494da8c18b0334f782ce4138872f8c7f5e254c5aecc3956e32fb542a2524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
